### ISSUE TITLE
Handle view with @Binding

### ISSUE THREAD

**Issue by cianiandreadev** [globulus/swiftui-flow-layout#10]
Hello,

I have a question regarding the library:
My "chips" are actually "selectable" and have an internal state (`isSelected`) that can be changed by the user by tapping on them.

Assuming the views I am passing to the FlowLayout has a binding I have the following problem:

```swift

@Binding var items: [SomeType]

FlowLayout(mode: .scrollable,
               binding: $items,
               items: items,
               itemSpacing: 4) {
      MyChip( ??? ) // How can I pass the binding here to have back the change of selected/unselected
    }.padding()
```

Am I misunderstanding something about how to use it?

Thanks for the help

**Comment by gordan-glavas-codecons** [comment]
If you plan to access the selected index (or indices) from the parent view, you need to use a Set that holds the selected items (multiselect) or hold the index of the selected item (single select). That has no bearing on this library, though, it is an issue that you have to resolve whenever you have a sequence of Views that are instantiated dynamically. Here's an example how to implement a single-select: https://swiftuirecipes.com/blog/swiftui-radio-buttons
