### ISSUE TITLE
The spacing is wrong for multiline items.

### ISSUE THREAD

**Issue by vmorris1959** [globulus/swiftui-flow-layout#2]
Please check the attached image showing the issue. Any idea how to fix it? Thanks

<img width="401" alt="Screenshot 2021-09-04 at 18 12 56" src="https://user-images.githubusercontent.com/34970021/132103078-7830360c-833d-41d1-94b1-03efd34af938.png">

**Comment by vmorris1959** [comment]
And if the multiline item is at the beginning then it overlaps the next line.

<img width="411" alt="Screenshot 2021-09-04 at 18 20 15" src="https://user-images.githubusercontent.com/34970021/132103161-7b221f05-7e3f-4cd8-aa76-100122265418.png">

**Comment by gordan-glavas-codecons** [comment]
I fixed this in 1.0.2, it should work now. Let me know if it works for your as well so that I can close the issue.

![Simulator Screen Shot - iPhone SE (2nd generation) - 2021-09-06 at 10 46 11](https://user-images.githubusercontent.com/6662291/132188971-dd0e2825-9b32-4be4-a6a0-0a0f9d10f091.png)

**Comment by vmorris1959** [comment]
For some reason it didn't work for multiline items at the beginning, middle and end. See the image at the end. But you're getting there ;-)

`FlowLayout(mode: .scrollable,
					   binding: .constant(5),
					   items: ["And then a very very very very very long long long long long long long one", "Some long item here", "And then some longer one",
							   "Short", "And then a very very very very very long long long long long long long one", "Items", "Here", "And", "A", "Few", "More",
							   "And then a very very very very very long long long long long long long one"]) {...}`

<img width="392" alt="Screenshot 2021-09-07 at 15 25 44" src="https://user-images.githubusercontent.com/34970021/132362205-78f2c440-d9e4-4304-894a-e8cf126b379b.png">

**Comment by vmorris1959** [comment]
The tricky one seems to be the last item because if I add a single-line item at the end, then the example above works fine.

`FlowLayout(mode: .scrollable,
					   binding: .constant(5),
					   items: ["And then a very very very very very long long long long long long long one", "Some long item here", "And then some longer one",
							   "Short", "And then a very very very very very long long long long long long long one", "Items", "Here", "And", "A", "Few", "More",
							   "And then a very very very very very long long long long long long long one", "short at the end"]) {...}`

<img width="400" alt="Screenshot 2021-09-07 at 15 33 18" src="https://user-images.githubusercontent.com/34970021/132363107-6a46f85d-af42-4877-8a9b-f4e7adcd75fe.png">

**Comment by gordan-glavas-codecons** [comment]
The issue you're seeing is because your data isn't unique - the last row and the one in the middle are the same string, so the layout moves the middle one to the top. Each data point should be unique, otherwise the layout can't work: :)

If you try:

```swift
["And then a very very very very very long long long long long long long one", "Some long item here", "And then some longer one", "Short", "1 And then a very very very very very long long long long long long long one", "Items", "Here", "And", "A", "Few", "More", "2 And then a very very very very very long long long long long long long one"]
```

It works as you'd expect:

![Simulator Screen Shot - iPhone SE (2nd generation) - 2021-09-08 at 10 56 33](https://user-images.githubusercontent.com/6662291/132479110-8334baf9-4f38-4753-ad62-698b40fc4055.png)

**Comment by vmorris1959** [comment]
But what if the data model can provide data that isn't unique like in my example? On real case scenarios that's not something you can rely on. Any ideas how to overcome this uniqueness issue? Thanks

**Comment by vmorris1959** [comment]
By the way, I know that by wrapping every string with a struct so each has its own unique id (e.g, UUID) that would solve it. I'm asking for more of a solution inside your component that will make it generic and usable even if the user provides an array of string literals where some are duplicates, like in my case.

**Comment by gordan-glavas-codecons** [comment]
Now that you mention it, it's actually quite easy to get this done. I've just published version 1.0.3 that removes the uniqueness and `Hashable` constraints on data.

**Comment by vmorris1959** [comment]
Yes, that solved it. Thanks.

Quick question not related to this issue, what is the purpose of the RefreshBinding? I mean, the component should refresh when the data changes, so is there any specific scenario where that RefreshBinding might be useful?

**Comment by gordan-glavas-codecons** [comment]
Yes, say you want to have a list of options in which one or more is selected, and you track the selected index elsewhere (not within the data array). When this index changes externally, the view would not refresh to reflect the change (at least that's how it work(s/ed?) on iOS 13), so you'd have to use the refresh binding to tell the view to render itself again.
